# Generated by Django 4.1.5 on 2023-01-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_notifyorder_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotifyOrder',
        ),
    ]
