# Generated by Django 4.1.5 on 2023-01-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(default='pics/400x300.png', upload_to='product_images'),
        ),
    ]
