# Generated by Django 4.1.5 on 2023-01-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='https://placeimg.com/803/338/any', max_length=255),
        ),
    ]
